apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: ui
  name: frontend-deployment
  labels:
    app: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: <provide ecr image>
        ports:
        - containerPort: 80